<Project Sdk="Microsoft.NET.Sdk">

  <!-- Project Properties -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <!-- Aot Properties -->
  <PropertyGroup>
	<IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <!-- Analyzer Properties -->
  <PropertyGroup>
	<AnalysisMode>All</AnalysisMode>
	<!-- 
      CA1707: Remove underscores from the type name (Native Interop and Consistency)
	  CA1008: Add a member that has a value of zero with a suggested name of 'None' (Native Interop)
	  IDE0130: Namespace does not match folder structure (Safer and simpler namespace for Native types)
    -->
	<NoWarn>$(NoWarn);CA1707;CA1008;IDE0130</NoWarn>
  </PropertyGroup>

  <!-- Libraries -->
  <ItemGroup>
    <None Update="oo2core_5_win64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="oo2core_6_win64.dll">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="oo2core_8_win64.dll">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="oo2core_9_win64.dll">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
	<None Update="liboo2corelinux64.so.5">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="liboo2corelinux64.so.6">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="liboo2corelinux64.so.8">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="liboo2corelinux64.so.9">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
	<None Update="liboo2coremac64.2.5.dylib">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="liboo2coremac64.2.6.dylib">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="liboo2coremac64.2.8.dylib">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="liboo2coremac64.2.9.dylib">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
	<None Update="oodleinterop.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
